### PR TITLE
Fixed Issue with Pressing Enter When Searching for Jobs

### LINKED ISSUE #144: Front end - Make hitting <enter> search and not refresh the page
When typing in the search bar, pressing enter should perform the same behaviour as pressing search.

### PR DESCRIPTION
**Pull request by cormacjmollitor**
Pressing enter in the search bar now calls the backend and populates the results table. Closes #144

### CODE REVIEW

**Review by cowmanjoe — COMMENTED** [review]
Are we using Redux? If so, then this all looks good, but I thought we were moving away from that because it was unnecessarily complex. If we are moving away from it I'd like to avoid any changes that add imports to redux so that we can remove it from the package.json. 

I don't really have a strong opinion on whether or not we should use it because I am not very familiar. I lean towards not using it because from what I've seen our front end doesn't need it (yet at least).

**Comment by cormacjmollitor** [comment]
@cowmanjoe We're probably not going to use Redux. This commit actually doesn't use Redux but uses a global store file store.js instead. I made a change to rename the Redux store file to reduxStore.js because it was named store.js before. If we're set on abandoning Redux, we can delete the reduxStore.js file and remove the imports for it.

File: client/src/reduxStore.js [hunk 1]
```diff
@@ -0,0 +1,10 @@
+import { createStore, applyMiddleware } from 'redux';
```
Comment (cowmanjoe) [inline client/src/reduxStore.js]: Isn't this from the redux package?

File: client/src/reduxStore.js [hunk 2]
```diff
@@ -0,0 +1,10 @@
...
+import thunk from 'redux-thunk';
```
Comment (cowmanjoe) [inline client/src/reduxStore.js]: I'm not sure what this is. Is it dependent on redux or something separate?

**Review by cowmanjoe — COMMENTED** [review]
Unless I'm mistaken it looks like you've added a couple of imports to redux or redux related packages.

**Comment by cowmanjoe** [comment]
Sorry I think I may have misunderstood your comment.

**Comment by cowmanjoe** [comment]
I see now. You renamed the store to reduxStore, but haven't deleted it yet because we're not sure about whether we're using it or not. Is that correct?

File: client/src/reduxStore.js (hunk 1 above)
Comment (cormacjmollitor) [reply client/src/reduxStore.js]: This was there before when it was store.js. I think it's just saying this is an addition because I renamed the file to reduxStore.js

File: client/src/reduxStore.js (hunk 2 above)
Comment (cormacjmollitor) [reply client/src/reduxStore.js]: Same here

**Comment by cormacjmollitor** [comment]
All good. Yeah, I just renamed it to reduxStore because even if we abandon Redux, we'll probably still want a global store file so I made a new one called store.js

**Review by cowmanjoe — APPROVED** [review]
Got it. Works well on my machine. It's so much nicer than it was before lol. 

I think if we are no longer using reduxStore we should just **delete it** because it's not much code and we can always find it from older commits if we need it again. It just reduces redundant code if we remove it. Do that **before merging** please, unless you disagree for some reason.

**Comment by cormacjmollitor** [comment]
I agree. I'll get rid of the redux store file and the imports for it before merging.
